### ISSUE TITLE
Where are the User Guide sources now?

### ISSUE THREAD

**Issue by hwellmann** [eclipse-ee4j/jsonb-api#105]
Which is now the official location for the User Guide from the JSON-B community website http://json-b.net/ (or in fact for the entire website)?

It looks like the User Guide used to be here
https://github.com/javaee/jsonb-spec/blob/master/docs/src/docs/user-guide.adoc

but this repository is archived, and I can't find any corresponding documentation in the current repository https://github.com/eclipse-ee4j/jsonb-api

**Comment by m0mus** [comment]
Here it is: https://github.com/eclipse-ee4j/jsonb-api/tree/master/docs
