### ISSUE TITLE
Update Scope Statement for Jakarta API for JSON Binding Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jsonb-api#124]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by m0mus** [comment]
Proposed new scope:

Jakarta API for JSON Binding provides a specification document, API and TCK that defines a binding framework for converting Java(R) objects to/from JSON documents.

**Comment by waynebeaton** [comment]
The project name (#125) will likely be "Jakarta JSON Binding".

How does this sound for the specification scope?

> Jakarta JSON Binding defines a binding framework for converting Java(R) objects to and from JSON documents.

**Comment by waynebeaton** [comment]
Apparently, we don't need the (R), so...

> Jakarta JSON Binding defines a binding framework for converting Java objects to and from JSON documents.

Good to go?

**Comment by waynebeaton** [comment]
Lazy consensus says yes.
