### ISSUE TITLE
Change project name to Jakarta JSON Binding

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jsonb-api#125]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Any objections to the name "Jakarta JSON Binding"?

**Comment by m-reza-rahman** [comment]
I think it is a good name.

**Comment by m0mus** [comment]
No objections
