### ISSUE TITLE
default JsonbPropertyOrder should be the order defined by its class

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/jsonb-api#170]
If no JsonbPropertyOrder is defined by the user, then Json-B should use the order defined by its class. For example:

```
class Item {
private int id; // first position
private String name;  // second position
private String description; // third position
}
```

**The default order should be the same as declaring this:**

```
@JsonbPropertyOrder(value = {"id", "name", "description"})
```

_tested with jakarta.json.bind-api v1.0.1_

**Comment by aguibert** [comment]
hi @nimo23, currently as[ defined by the spec](http://json-b.net/docs/user-guide.html#properties-order) the default property order is LEXIOGRAPHICAL which means properties are ordered A-Z.

If you specify `@JsonbPropertyOrder(PropertyOrderStrategy.ANY)` the order will be undefined, but typically it will end up being the order that fields are defined in the class which is what you are requesting.

Unfortunately we can't make the order defined in the class the default option for 2 reasons:
1. The spec explicitly defines the default ordering already, and changing this would be a breaking change, and we would not want to do that without a strong reason. If the spec left the default ordering undefined, then we could have defined it to something in a future version of JSON-B.
2. There is no Java API that returns fields/methods back in the order they are defined in the class. Typically[ reflection operations](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--) will return classes/methods back in the order they are defined in the class file, but this is not guaranteed by the javadoc and therefore would not be safe to define as a behavior.

**Comment by nimo23** [comment]
>if you specify @JsonbPropertyOrder(PropertyOrderStrategy.ANY) the order will be undefined, but typically it will end up being the order that fields are defined in the class which is what you are requesting.

With yasson, the order with `PropertyOrderStrategy.ANY` is arbitrarily.

I found it may be done in future:

https://github.com/eclipse-ee4j/yasson/issues/266
