### ISSUE TITLE
TCK wrongly test GregorianCalendar

### ISSUE THREAD

**Issue by rmannibucau** [eclipse-ee4j/jsonb-api#177]
Hi,

Not sure where TCK are but I'd like to report that they likely assume they run on a particular implementation - which is wrong from a spec perspective.

com.sun.ts.tests.jsonb.defaultmapping.dates.DatesMappingTest#testGregorianCalendarWithTimeMapping uses GregorianCalendar#equals to compare serialized and deserialized instances which basically means the way the instance is built - and not its value - is validated. This is likely wrong since JSON-B can only guarantee the value.

**Comment by jansupol** [comment]
1) The TCK repo is [here ](https://github.com/eclipse-ee4j/jakartaee-tck)
2) The test is [here](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonb/defaultmapping/dates/DatesMappingTest.java)
2) Do you refer to `b.equals(orig.getTime())` or what `equals`?

**Comment by rmannibucau** [comment]
@jansupol yes, the default equals is used for the mentionned test, i.e. com.sun.ts.tests.jsonb.MappingTester#testUnmarshall which just do an equals (no getTime() or so).

**Comment by jansupol** [comment]
Can you please point to the line in [MappingTester](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonb/MappingTester.java)?

**Comment by rmannibucau** [comment]
sure,

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonb/MappingTester.java#L70 which is used since https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonb/defaultmapping/dates/DatesMappingTest.java#L270 does not override it.

For reference, some other tests fix it: https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonb/defaultmapping/dates/DatesMappingTest.java#L248

**Comment by jansupol** [comment]
[This ](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jsonb/defaultmapping/dates/DatesMappingTest.java#L270) seems to be the only case using GregorianCalendar. Do the other tests work for you? Can you please file a bug in the [TCK issue tracker](https://github.com/eclipse-ee4j/jakartaee-tck/issues)?

**Comment by rmannibucau** [comment]
Done at https://github.com/eclipse-ee4j/jakartaee-tck/issues/102, thanks for the help @jansupol

**Comment by jansupol** [comment]
Closing this in favor of the new bug
