### ISSUE TITLE
Deserialization from null to JsonValue

### ISSUE THREAD

**Issue by leadpony** [eclipse-ee4j/jsonb-api#181]
According to the current spec, mapping JSON document
```json
{
    "value": null
}
```
to the following Java class
```java
public class Stuff {
    public JsonValue value;
}
```
assigns `null` to the `value` in the class instead of `JsonValue.NULL`.

On the other hand, the following JSON document
```json
{
    "value": {
        "value2": null
    }
}
```
assigns a JSON object to the `value` and `JsonValue.NULL` is assigned to its `value2` property.

I believe `null` in JSON should be converted to `JsonValue.NULL` if the target type is `JsonValue`, in the same way it is converted specially to `Optional.empty()` when the target type is `Optional`.

Please see also eclipse-ee4j/yasson#293

**Comment by m0mus** [comment]
Technically you can assign `null` to your value field. Java allows it. Although it could not make sense some users may use it and there won't be any option to do it unless you skip the field in your Json.

**Comment by leadpony** [comment]
Java allows for developers to assign `null` to any value of `Optional<T>` type. However the JSON-B API assigns `Optional.empty()` instread of `null` for it. 
The most preferable value to be mapped from JSON null depends on the target type. 
For `Optional<T>` it is `Optional.empty()` and for `JsonValue` it is `JsonValue.NULL`.
Many JSON-P users appreciate the existence of `JsonValue.NULL` in JSON-P spec, because it free us from notorious`NullPointerException`.
It is OK for me that the API change will happen in 2.0 or later.  We can use setter method forcing to assign `JsonValue.NULL` when the passed value is`null`.

**Comment by rmannibucau** [comment]
In jsonb, jsonvalue should be a fallback when nothing matches - otherwise you use a deserializer (from jsonb if local) if you need json metadata and not only binding. So we shouldnt encourage it.

Now, the original json really has jsonvalue.null so it must be injected as such for jsonvalue type. However, an empty json would bind java null and not any jsonvalue instance to respect the binding.

Does it sound ok?

**Comment by leadpony** [comment]
Yes.
If the input JSON is `{ }`, `Stuff.value` should not be modified and be kept as initial `null` (of Java) in this case, which means the property does not exist in the JSON.
If the input JSON is `{ "value": null }`, `Stuff.value` should be modified to `JsonValue.NULL`, which means the property actually exists in the JSON and its value is JSON null.

**Comment by m0mus** [comment]
After some thinking I am fine to add to 2.0 spec feature set.
