### ISSUE TITLE
with(De)serializers(Jsonb(De)serializer, Class...)

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jsonb-api#184]
I'd like to propose the following variant of the `with`(De)serializers` configuration builder method:
```java
public final JsonbConfig with(De)serializer(Jsonb(De)serializer, Class<?>... classes)
```
This would allow to programmatically assign a specific deserializer to one particular class or interface *at runtime* just like the `@JsonbType(De)serializer` does this *at compile time*.

This is needed in case the class actively marshalling / unmarshalling the node tree is developed independently from the actual node tree classes: There might be cases (I just had one) where the party developing the node tree classes simply do not know that the other team actually will apply JSON-B to them or do not know that team at all.

**Comment by rmannibucau** [comment]
Hi @mkarg,

I don't see why

> This would allow to programmatically assign a specific deserializer to one particular class or interface at runtime just like the @JsonbType(De)serializer does this at compile time.

is true.

Current API covers that since the type is determined from the (de)serializer generics. It also means the generics of the classes and (de)serializers must match.

Do you intend to enable generics (de)serializers - i.e. not typed - and an unsafe configuration for them? I'm not sure it would be good and it is always trivial to stringly type them in user code (a 1 liner "extends") so think JSON-B already covers this use case.

Wdyt?

Romain

**Comment by mkarg** [comment]
It would be nice if that would be true. Actually Johnzon does not allow to programmatically register Deserializers at all (tried it and it said it only supports annotations), while Yasson runs the Deserializer always (it ignores the generic type).

**Comment by rmannibucau** [comment]
@mkarg next johnzon release will pass JSONP/JSONB TCK and support it properly https://github.com/apache/johnzon/blob/master/johnzon-jsonb/src/test/java/org/apache/johnzon/jsonb/SerializerTest.java#L192. Last one had a bug for root objects (was supported for nested objects only). But still, the spec is already good about that feature, no?

**Comment by mkarg** [comment]
If yasson's behavior (running programmatically registered deserializers on ANY class, not just on the generic type) is *definitively* a bug of thar product, then the existing spec is ok for me and we do not *need* this additional method.

On the other hand, it would be *convenient* to be able to use this new method, because it is painful to always have to subclass created just for the sake of per-type registration. :-)

**Comment by rmannibucau** [comment]
Yasson passes TCK too (the linked test is almost a copy of a TCK test) so it must be compliant.

So yes, the point is: how to register generic serializers. Think the answer is that they should be typed, like MySerializer<? extends Foo> so while there is a type it is good. Otherwise it means you just reimplemented Jsonb itself. Do I miss a case it can be useful to explicit that through a method signature?

**Comment by mkarg** [comment]
If Yasson really passes the TCK then we have a problem! @m0mus Can you please shed some light on this? Is it a bug in Yasson + TCK, or is it the spec being not tight enough (so we need this new method)?

**Comment by mkarg** [comment]
Romain, maybe you misunderstood me. Certainly the serializers should be *typed*, but you unfortunately *cannot* write `withDeserializers(MyDeserializer<MyInterface>.class)` but instead you need to explicitly subclass it. *That* is what I meant with "unconvenient". Writing `withDeserializer(MyDeserializer.class, MyInterface.class)` might look not typesafe *enough*, but at least it is much easier to write *and* the reader directly sees what nodes the deserializer will be bound to!

**Comment by rmannibucau** [comment]
@mkarg yep but if you have MyDeserializer<T> then T is likely bounded so it can be registered globally already and have the needed logic to use serialization context to passthrough the rest of the serialization. If not desired then you rewrote a generic serializer so you rewrote jsonb (and you can get jsonb instance in serializer if really desired) so not sure the current issue we are trying to solve.
On the interface point, note that we should probably rather materialize the interface by an implementation for deserialization and serialization does not need a serializer more than any other class so back to generic point which sounds good to me.

**Comment by mkarg** [comment]
Sorry but I can't follow you... For example if I want to register Johnzon Extra's polymorphic Deserializer programmatically for processing *any* (even unknown-from-third-party or to-be-done-in-future) classes having implemented interface `X`, how to do type-safe that *without* subclassing it? `X` exists solely to hold `@JsonChildren`, so there is actually no need to make it a class. I do not see how anything you say would be easier to use or more convenient or better to read or more feasibly that using my new method. I understand that it is not *necessary* but it is *far* more convenient.

**Comment by rmannibucau** [comment]
Im not saying it is easier, it is actually not, but it does not bring anthing you cant already do. withXxx(new My<X>(){}) works. It is reversed to what your propose but is 1-1 without duplicating a method which is no more type safe.

So overall I dont see a single use case your new API handles we dont already have handy. This is why I asked a real life example to try to go through my abstraction "blindness".

**Comment by mkarg** [comment]
What you do above *is* subclassing, which *is* what I want to get rid of.

Anyways, yesterday I already agreed that the new API is not solving something *unpossible*, but it is just for *convenience*, maybe you missed that:

> If yasson's behavior (running programmatically registered deserializers on ANY class, not just on the generic type) is _definitively_ a bug of thar product, then the existing spec is ok for me and **we do not _need_** this additional method.

> On the other hand, **it would be _convenient_** to be able to use this new method, because it is painful to always have to subclass created just for the sake of per-type registration. :-)

So if JSON-B strives to *just* implement that *smallest possible* set of methods (i. e. does *not* strive for *convenience*) we must close this issue.

**Comment by rmannibucau** [comment]
@mkarg yes but subclassing inline so syntaxically it solves your verbosity/convenience issue. It also solves the type issue (keep in mind anything done for Class requires to be done for Type, in particular with the interfaces support you mentionned).

**Comment by mkarg** [comment]
@rmannibucau I wouldn't say that subclassing becomes *convenient* by inlining it, but I see your point.  ;-)

I am fine with closing this issue as apparently there is no majority of committers interested in supporting it. Again, I want to stress that it is really important that the mentioned bugs in Yasson and Johnzon are understood as a proof that the TCK seems to miss something, as it did not detect that effectively both products fail in this area.

**Comment by rmannibucau** [comment]
@mkarg about tck: johnzon just passed them on master - thanks jakarta/eclipse to made it public ;) , and yasson just asked its certification as part of jakarta process, so I would delay a bit the issue to ensure it is really accurate but I agree it must be checked cause it would be serious if true.

**Comment by mkarg** [comment]
@rmannibucau Wait until what or when?

**Comment by rmannibucau** [comment]
@mkarg TCK compliants releases are out there

**Comment by mkarg** [comment]
@rmannibucau I will open an issue in the spec's tracker as a reminder. Otherwise I will forget.

**Comment by mkarg** [comment]
> @rmannibucau I will open an issue in the spec's tracker as a reminder. Otherwise I will forget.

Replacing #184 by #185. Thanks for all, Romain! :-)
