### ISSUE TITLE
Strategy for JSON-B versions going forward

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/jsonb-api#204]
Currently JSON-B 1.0 has been released and is part of Java EE 8 and Jakarta EE 8 platform.

For Jakarta EE 9 we _will_ need to move to the `jakarta.*` package namespace, regardless of if "big bang" or "incremental" approach is taken. This means according to semantic versioning rules we will need to update to JSON-B 2.0. I expect that Jakarta EE 9 will be a "package update only" release.

For Jakarta EE 10, we can finally make some real changes to the API/Spec/TCK. This is where we can add new planned features outlined in the vNext board: https://github.com/eclipse-ee4j/jsonb-api/projects/1

-----

## Proposed branching strategy

1. Leave the existing `1.0-1.0.2` branch for JSON-B 1.0 service work.
2. Do the `javax.*` --> `jakarta.*` package rename, cut that as the `2.0` branch. This is also blocked by JSON-P doing their package rename and creating some sort of release.
3. The resulting `master` branch will eventually become JSON-B 2.1 which will be included in Jakarta EE 10 and is where we will be able to do our forward development work.

**Comment by m0mus** [comment]
I think that we should use `master` for the next release. I mean that `javax->jakarta` rename should be done in `master`. We will branch our 2.x after 2.0 official release.
