### ISSUE TITLE
Ability to register Serializers/Deserializers/Adapters in runtime

### ISSUE THREAD

**Issue by phillip-kruger** [eclipse-ee4j/jsonb-api#211]
Hi All.
Not sure if this already possible, if so, please let me know how I can do this.

I want to create Serializers, Deserializers and Adapters during runtime. 

I do not know the class that I want to apply this on at compile time and only discover them at runtime and would like to be able to register them on the fly.

I need this when implementing MicroProfile GraphQL. I need to basically be able to Serializers/Deserializers but taking the GraphQL annotations into account. 

Alternatively if I can create a Serializers Deserializers for Any Object, and then decide if this object is one I care about, and if not just proceed.

Hope this makes sense.

Thanks

**Comment by rmannibucau** [comment]
Hi @phillip-kruger , sounds like reimplementing JSON-B interpolating just a bit what you describe?
Here a few things you can consider:

1. Discover the types at startup time with CDI scanning (should be ok for Microprofile introspecting JAXRS endpoint or using a declarative annotation as openapi api does for requests/responses)
2. You can create a JSON-B instance lazily per aggregate which is highly customized

**Comment by phillip-kruger** [comment]
Hi @rmannibucau . Thanks for getting back to me :)

So I already know (discovered) all the types at startup, how do I create the JSON-B instance as you describe ? (Any documentation available ?)

**Comment by aguibert** [comment]
@phillip-kruger the key will be that you need to create the adapters/[de]serializers before you create the `Jsonb` instance, since config for `Jsonb` cannot be altered once the instance is instructed.

Assuming you know all this info up front, you could potentially use a bytecode library like ASM to generate the classes at runtime and then register them.

This is certainly an odd case, so it's not something we would document in the JSON-B doc. However, here is a PR where one of my Quarkus teammates was going to generate custom serializers programmatically at native-mode build time using ASM: https://github.com/quarkusio/quarkus/pull/3553

**Comment by phillip-kruger** [comment]
Hi @aguibert - Thanks for your reply.

> the key will be that you need to create the adapters/[de]serializers before you create the Jsonbinstance, since config for Jsonb cannot be altered once the instance is instructed.

That is not a problem. I can do that. My issue is that I discover the classes in runtime and want a programmatic way to add a new serializers for a certain object type. I assume somewhere there is a map of some sort that contain all serializers mapped by type ?
Thanks for the link, I'll have a look. 

Do you know if I can do this in Yasson directly ?

**Comment by rmannibucau** [comment]
@phillip-kruger not sure I got the question right but had https://github.com/eclipse-ee4j/jsonb-api/blob/master/api/src/main/java/javax/json/bind/JsonbConfig.java#L338 (and the symmetric method) in head

**Comment by aguibert** [comment]
@phillip-kruger not quite sure what you mean about this part? 
` I assume somewhere there is a map of some sort that contain all serializers mapped by type ?`

If you have class `Foo` you can generate a class like:
`class FooSerializer implements JsonbSerializer<Foo> {`
and register it with the `JsonbConfig` you use to create your `Jsonb` object, then the JSON-B impl will take care of the rest of the mapping

**Comment by phillip-kruger** [comment]
Yes, thanks both of you. So what I am looking for is something like this.
`class GeneralSerializer implements JsonbSerializer {`

without the generic type <Foo> (as I do not know that.

Then I want to use JsonbConfig like this:
`new JsonbConfig().withSerializer(Class forType, new GeneralSerializer());`

Does this makes sense ?

**Comment by aguibert** [comment]
I think you can create a generic serializer like that (essentially `JsonbSerializer<Object>`), but at that point I would question what value JSON-B is adding, since you are going to be doing all of the nested object parsing on your own essentially. Perhaps JSON-P would be a better solution at that point?

**Comment by phillip-kruger** [comment]
Tried that, it's not being executed. And without a type I get an error...
Do you have an example where `<Object>` is working ?

**Comment by rmannibucau** [comment]
It must not work but just recreate a jsonb instance with concrete types you know lazily.
Can need to visit the class first but it is not a blocker imho.
As pointed out twice, if you want to reimplement jsonb dont use jsonb ;).
What would be the custom serializer added value?

**Comment by aguibert** [comment]
here is a working example of a generic Object Serializer, but as you can see it's pretty much re-implementing JSON-B:
```java
    public static class Dog {
        public String name;
        public int age;
    }

    public static class MySerializer implements JsonbSerializer<Object> {
        @Override
        public void serialize(Object obj, JsonGenerator generator, SerializationContext ctx) {
            System.out.println("serialize: " + obj);
            generator.writeStartObject();
            if (obj instanceof Dog) {
                Dog d = (Dog) obj;
                generator.write("@@name", d.name);
                generator.write("@@age", d.age);
            }
            generator.writeEnd();
        }
    }

    private static final Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withSerializers(new MySerializer()));

    public static void main(String args[]) throws Exception {
        new AGGMain().go();
    }

    public void go() throws Exception {
        System.out.println("Starting  ");
        Dog d = new Dog();
        d.name = "Spot";
        d.age = 42;
        System.out.println("JSON " + jsonb.toJson(d));
    }
```

Perhaps you could include a minimal concrete example of what you are attempting to accomplish? I'm not quite sure what the resulting output you are after (I have some guesses from googling GraphQL but don't want to assume)

**Comment by phillip-kruger** [comment]
Thanks @aguibert . I'll try it again tomorrow. I'll send you an example, but basically we want to support jsonb annotations, and also some GraphQL annotations that does the same thing.

**Comment by phillip-kruger** [comment]
Hi @aguibert . So it seems like it's an older version that is giving me the issue of <Object> not working.

See https://github.com/phillip-kruger/jsonb-object-test

Using the latest JSON-B and JSON-P (and yasson) everything works. 
Reverting to older version (as used by the application server) it does not :(

Thanks again for your help. I still think it would be cool to be able to register new types on the fly (not using generics) but understand it the workgroup don't want to add that feature.

Thanks

**Comment by phillip-kruger** [comment]
Narrowed it down to yasson. Has to be > version 1.0.2

**Comment by aguibert** [comment]
Glad upgrading to a newer version of Yasson fixed it.

I'm not quite sure what `register new types on the fly` would look like, could you propose a mockup of what you had in mind?

**Comment by phillip-kruger** [comment]
`new JsonbConfig().withSerializer(Foo.class, new GeneralSerializer());`

Here my original problem I am trying to solve. We have a few GraphQL annotations, to change the behaviour when  Serializers/Deserializers objects (or part there of) in GraphQL.

We decided to also support Json-B annotation, in case the user is already using Json-B. So I want to  Serializers/Deserializers using Json-B but also look for some more annotations (for naming the fields and ignore, etc)

**Comment by rmannibucau** [comment]
think we are discussion this mode in other issue. mainly about a way to change portably the read annotations. in johnzon you have AccessMode to do that, in yasson there is another internal but we don't have yet a portable model. Serializers are not for that IMO.

**Comment by phillip-kruger** [comment]
Ok cool, so we can close this issue and I'll wait until there is a way to do this. Thanks for all the help !

**Comment by rmannibucau** [comment]
ref: https://github.com/eclipse-ee4j/jsonb-api/issues/88
