### ISSUE TITLE
When PropertyNamingStrategy is specified, properties may not be printed.

### ISSUE THREAD

**Issue by Empressia** [eclipse-ee4j/jsonb-api#212]
Payara Micro 5.194（JDK11）でJAX-RSを使用しているときに、  
Json-BのPropertyNamingStrategyを指定したら、  
オブジェクトのプロパティがシリアライズされませんでした。  

テストコードを書きました。  
https://github.com/Empressia/JsonBTest01  
https://github.com/Empressia/JsonBTest01/blob/master/src/test/java/jp/empressia/test/jsonb/JsonBTest01.java  

シリアライズしたクラス：  
```java
	public static class SomethingClass {
		@SuppressWarnings("unused")
		private String Subject = "Field";
		public String getSubject() {
			return "Getter";
		}
	}
```
↓
テスト結果：  
```
Expected: is "{\"Subject\":\"Getter\"}"
     but: was "{}"
```

フィールドを削除するとテストは通ります。

**Comment by aguibert** [comment]
Issue moved to [eclipse-ee4j/yasson #371](https://github.com/eclipse-ee4j/yasson/issues/371) via [**ZenHub**](https://www.zenhub.com/)

**Comment by aguibert** [comment]
This looks like a bug in Yasson rather than the JSON-B API, moving this issue to https://github.com/eclipse-ee4j/yasson/issues/371
