### ISSUE TITLE
@JsonbTypeDeserializer and @JsonbTypeSerializer don't work in the fields

### ISSUE THREAD

**Issue by lusabo** [eclipse-ee4j/jsonb-api#235]
I'm in an activity of exchanging **Jackson** for **Jsob-B** and I am having a problem on use **@JsonbTypeDeserializer** and **@JsonbTypeSerializer** as told below.

I have an entity like this:

     public class User implements Serializable {
      
      private static final long serialVersionUID = 1L;

      private String login;

      @JsonbTypeDeserializer(Decrypting.class)
      @JsonbTypeSerializer(Encrypting.class)
      private String password;

      // getters and setter
    }

And one test like this:
  

      @Test
      public void whenDeserializingUsingJsonbTypeDeserializer() throws IOException {
    
        String json = "{\"login\":\"admin\", \"password\":\"yfv_ntl3_Nbrv0139tDwRQ\"}";
    
        Jsonb jsonb = JsonbBuilder.create();
    
        User user = jsonb.fromJson(json, User.class);
    
        Assert.assertEquals(user.getPassword(), "test-string");
      }

When running the test, the Decryption class is trying to deserialize the **login** field, but, as you can see, only the **password** field has the annotations.

Any way to fix it?

**Comment by aguibert** [comment]
hi @lusabo, thanks for raising this issue. Can you please include the code for the `Encrypting` and `Decrypting` classes referenced in the annotations?

**Comment by lusabo** [comment]
Hi @aguibert , follow the codes:

```
public class DecryptingValueConverter implements JsonbDeserializer<String> {

  @Override
  public String deserialize(final JsonParser jsonParser, final DeserializationContext deserializationContext, final Type type) {
    String encryptedValue = jsonParser.getString();
    try {
      return EncryptDecryptUtil.decrypt(encryptedValue);
    } catch (GeneralSecurityException e) {
      throw new IllegalArgumentException("Could not decrypt value", e);
    }
  }
}
```


```
public class EncryptingValueConverter implements JsonbSerializer<String> {

    @Override
    public void serialize(final String decryptedValue, final JsonGenerator jsonGenerator, final SerializationContext serializationContext) {
        try {
            jsonGenerator.write(EncryptDecryptUtil.encrypt(decryptedValue));
        } catch (GeneralSecurityException e) {
            throw new IllegalArgumentException("Could not encrypt value", e);
        }
    }
}
```

**Comment by aguibert** [comment]
ok, everything appears to be written correctly. I suspect it is an implementation bug -- which JSON-B impl are you using? (probably Yasson or Johnzon)

**Comment by lusabo** [comment]
Yasson.
