### ISSUE TITLE
JSON-B / Yasson is ignoring the new JsonbConfig :: withDeserializers

### ISSUE THREAD

**Issue by lusabo** [eclipse-ee4j/jsonb-api#238]
I am migrating a project from Jackson to Json-B (Yasson v. 1.0.7), and the code below is to ilustrate a scenario that is ocurring with me.

I have a json file like this:

    {
      "response": {
        "accessories": {
          "accessory": [
            {
              "finance": "mandatory",
              "type": "INDIVIDUAL"
            },
            {
              "finance": "optional",
              "type": "ORIGINAL"
            },
            {
              "finance": "not",
              "type": "TRADE"
            }
          ]
        }
      }
    }

I am rewriting one test like below:

    @Test
    public void testDeserialize() {

        final JsonbConfig config = new JsonbConfig()
                .withSerializers(new MySerializer())
                .withDeserializers(new MyDeserializer());

        final Jsonb jsonb = JsonbBuilder.create(config);

        final InputStream data = this.getClass().getClassLoader().getResourceAsStream("response.json");

        final Response obj = jsonb.fromJson(data, Response.class);

        final Accessories accessories = obj.getAccessories();

        assertThat(accessories.getAccessory().isEmpty(), is(false));
    }
	
The code of the class MyDeserializer is:
```
public class MyDeserializer implements JsonbDeserializer<FType> {
    @Override
    public FType deserialize(JsonParser parser, DeserializationContext context, Type type) {
        return FType.MANDATORY;
    }
}
```

The problem is when I run the test the deseralizator is not called and the property **accessory** from object **obj** is null.

How to solve it?

**Comment by aguibert** [comment]
hi @lusabo, I see that you posted the same question on the JSON-B repo here: https://github.com/eclipse-ee4j/jsonb-api/issues/238

I'm going to close this issue so people don't duplicate work answering the same question in different places

**Comment by aguibert** [comment]
hi @lusabo, I see you posted the same question on the Yasson repo here: https://github.com/eclipse-ee4j/yasson/issues/406

I'm going to close this issue so that people don't duplicate effort answering the same question in two places.
