### ISSUE TITLE
Compatibility Certification Request for Eclipse Yasson 2.0.0

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsonb-api#257]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  [Eclipse Yasson 2.0.0](https://github.com/eclipse-ee4j/yasson/releases/tag/2.0.0-RELEASE)
- [x] Specification Name, Version and download URL\
   [Jakarta JSON Binding 2.0](https://jakarta.ee/specifications/jsonb/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta JSON Binding TCK 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jsonb-tck-2.0.0.zip), SHA-256: 7f3d072602f8935e46cf6ec94b0418af88cce176aa999b7a6a8701c7b9f65a52
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/yasson/tck/TCK-results.html)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by scottkurz** [comment]
@m0mus I was looking at what the other specs did for the CCR issue and noticed you too had never closed yours after the spec wa approved.    I spoke with Ed Bratt and he said the API project can go ahead and close the CCR issue and add the "Accepted" label .. so you can probably do this yourself assuming no objections have been raised.  (I haven't been following myself).

**Comment by lukasj** [comment]
I think there is "lazy consensus" after 2 weeks (maybe just 1 week) defined somewhere...
