### ISSUE TITLE
UntypedMappingTest.testArrayMapping tck test should fail

### ISSUE THREAD

**Issue by Verdent** [eclipse-ee4j/jsonb-api#267]
I have encountered some strange behavior in [UntypedMappingTest.testArrayMapping](https://github.com/eclipse-ee4j/jsonb-api/blob/c74a6f215b054c3f8f72c2b5b6c2b4afd43c857c/tck/src/main/java/jakarta/json/bind/tck/defaultmapping/untyped/UntypedMappingTest.java#L128) test.

The test itself is using SimpleMappingTester class and passes List instance to its test method. This test method, on the [line 46](https://github.com/eclipse-ee4j/jsonb-api/blob/c74a6f215b054c3f8f72c2b5b6c2b4afd43c857c/tck/src/main/java/jakarta/json/bind/tck/SimpleMappingTester.java#L46) marshalls List to the json, but the [runtime type provided](https://github.com/eclipse-ee4j/jsonb-api/blob/c74a6f215b054c3f8f72c2b5b6c2b4afd43c857c/tck/src/main/java/jakarta/json/bind/tck/SimpleMappingTester.java#L106) is actually TypeContainer class. I would assume that runtime type should be exact/more precise type of the handled instance. Therefore I think this test is not correct and it should fail since this List should be handled as TypeContainer instance in this case.

Is this proper behavior? Should I make a fix for the issue?

**Comment by edbratt** [comment]
Apologies for resurrecting this issue -- it appears this challenge was accepted -- was it actually a challenge, or just a bug? If it was a challenge, there should be either an accepted or invalid label attached. If it isn't a challenge, and it's just a bug in the TCK being developed, then the challenge label ought to be removed. Going further, if it was a successful challenge, there ought to be a record of a disabled test followed by a bug-fix update release to the TCK (bump the micro-version ID).
