### ISSUE TITLE
json-b.net does not resolve

### ISSUE THREAD

**Issue by ljnelson** [eclipse-ee4j/jsonb-api#292]
The "official website" linked in the `README.md` does not resolve as of 2021-11-13: http://json-b.net

**Comment by rgmz** [comment]
There's an [Archive of the website from August 2021](https://web.archive.org/web/20210812220623/http://json-b.net/); hopefully it will resolve again soon.

**Comment by ljnelson** [comment]
This now (2021-12-03) leads to a hacked website.

**Comment by m0mus** [comment]
A link in README has been updated and it points to the right web site. jsonb-b.net domain has been expired and we don't use it anymore.
