### ISSUE TITLE
Support Optional<primitive> in @JsonbCreator

### ISSUE THREAD

**Issue by dansiviter** [eclipse-ee4j/jsonb-api#307]
Related to #121, new spec. doesn't mention `OptionalInt`, `OptionalLong` and `OptionalDouble` primitive wrappers. So small clarification to the spec. to permit these types.

**Comment by Verdent** [comment]
Each of the Optional types is not listed explicitly, but I would say this is covered by the following sentence: 
`If the parameter is any type other than Optional or its variations, then the null value is used. If the parameter is Optional or its variations, then the corresponding empty object must be used.`

**Comment by rmannibucau** [comment]
+1 to clarify it, @dansiviter think you can feel free to PR the text clarification

**Comment by Verdent** [comment]
+1 Sure, I am not against it :-)

**Comment by dansiviter** [comment]
@rmannibucau Ahhh, that's some subtle wording, thanks for pointing it out. I suppose it is sufficient as it is and hopefully implementors honour it.
