### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jsonb-api#85]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by jeyvison** [comment]
I'll work on this one

**Comment by jeyvison** [comment]
@m0mus , i'm gonna need the ssh keys for the jenkins job. I dont have access to this info.

**Comment by jeyvison** [comment]
@m0mus , just found out that jenkins and the OSS repository are already created:

See https://ci.eclipse.org/jsonb/ and
https://issues.sonatype.org/browse/OSSRH-41914

Dont know who is responsible , though

**Comment by m0mus** [comment]
@Tomas-Kraus did that. It looks like he forgot to assign himself to this task.

**Comment by Tomas-Kraus** [comment]
Yes, I'm working on regular buld and release jobs. But I'm on vacation this week.

**Comment by m0mus** [comment]
Jenkins job is created:
https://ci.eclipse.org/jsonb/job/jsonb-master-build/
